import fastf1
import joblib 
import pandas as pd
import numpy as np

from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

#read csv generated by collect_data.py
df = pd.read_csv("f1_race_data.csv")
print("\nMissing values:")
print(df.isna().sum())

print("Dataset shape:", df.shape)

# Convert categorical variables into numbers
df = pd.get_dummies(df, columns=["driver", "team", "track"])

# Split data chronologically
train_df = df[df["year"] <= 2023]
validation_df = df[df["year"] == 2024]
test_df = df[df["year"] == 2025]


# Separate features and target
X_train = train_df.drop("finish_pos", axis=1)
y_train = train_df["finish_pos"]

X_validation = validation_df.drop("finish_pos", axis=1)
y_validation = validation_df["finish_pos"]

X_test = test_df.drop("finish_pos", axis=1)
y_test = test_df["finish_pos"]


# Make sure all datasets have the same columns -> new drivers/old driver issues
X_validation = X_validation.reindex(
    columns=X_train.columns,
    fill_value=0
)

X_test = X_test.reindex(
    columns=X_train.columns,
    fill_value=0
)

# Create model that will continuously improve -> using pipeline to handle missing values
model = make_pipeline(
    SimpleImputer(strategy="median"),
    GradientBoostingRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    )
)


# Train model
model.fit(X_train, y_train)

# Evaluate on validation data
validation_pred = model.predict(X_validation)

validation_mae = mean_absolute_error(
    y_validation,
    validation_pred
)

print("Validation MAE:", validation_mae)

# Evaluate on final test data
test_pred = model.predict(X_test)

test_mae = mean_absolute_error(
    y_test,
    test_pred
)

print("Test MAE:", test_mae)