import fastf1
import joblib 

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

#read csv generated by collect_data.py
df = pd.read_csv("f1_race_data.csv")

# Convert categorical variables into numbers
df = pd.get_dummies(df, columns=["driver", "team", "track"])

# Split data chronologically
train_df = df[df["year"] <= 2023]
test_df = df[df["year"] > 2023]


# Separate features and target
X_train = train_df.drop("finish_pos", axis=1)
y_train = train_df["finish_pos"]

X_test = test_df.drop("finish_pos", axis=1)
y_test = test_df["finish_pos"]


# Create model that will continuously improve
model = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)


# Train model
model.fit(X_train, y_train)

# Make predictions
pred = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(y_test, pred)
print("MAE:", mae)

# Save model
joblib.dump(model, "f1_model.pkl")

print("Model saved!")